[[constraint]]
  name = "google.golang.org/appengine"
  version = "1.0.0"

[[constraint]]
  name = "gopkg.in/yaml.v2"
  version = "2.1.1"

[prune]
  go-tests = true
  unused-packages = true
  non-go = true
